[package]
name = "day-007-enums"
version = "0.1.0"
authors = ["VeliG <vgebrev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
